### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by handaru** [pmb0/express-tsx-views#160]
When I implement style, that's not working.

import React from "react";

export interface Props {
  title: string;
  lang: string;
}

// Important to use the `default` export
export default class MyView extends React.Component<Props> {
  render() {
    const spanStyles = {
      color: "blue",
      borderColor: "red",
    };

    return (
      <span style={spanStyles}>
        Hello from React! {this.props.title}, This is a(n) {this.props.lang}{" "}
        greating.
      </span>
    );
  }
}

**Comment by handaru** [comment]
Even if use:

<style
          dangerouslySetInnerHTML={{
            __html: `body {
                            background-color: lightblue;
                          }`
          }}
        />

**Comment by pmb0** [comment]
I have just tried it out. It works:

![image](https://user-images.githubusercontent.com/2140915/137458384-e7fcf97d-f0ff-4f31-af48-445fe1432bc4.png)

![image](https://user-images.githubusercontent.com/2140915/137458409-023406d3-171f-4ef1-b7db-6e26124f5462.png)
