### ISSUE TITLE
Nest.js Setup Throws Error For App Context

### ISSUE THREAD

**Issue by jared-leddy** [pmb0/express-tsx-views#337]
Example From Readme:
```js
setupReactViews(app, {
  viewsDirectory: resolve(__dirname, "views"),
  prettify: true, // Prettify HTML output
});
```
When this is used inside Nest.js `bootstrap()` function, we get errors regarding the app context. In the NPM module, it clearly shows `app: Application`, where Application is imported from Express. This means that we can't use this method in the Nest.js apps. In a Nest.js app, the app context is `NestExpressApplication`. 

Please provide the Nest.js examples for usage, specifically, for this package and not the nestjs-tsx-views.

I'm hoping that it's as simple as 
```js
app.setViewEngine('tsx');
```

**Comment by pmb0** [comment]
I made `nestjs-tsx-views` for this purpose.
