### ISSUE TITLE
TypeError: Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by Dav3rs** [pmb0/express-tsx-views#44]
#### When I use HMR the hot module replacement mode in nestjs this is the error:

![imagen](https://user-images.githubusercontent.com/50024128/95030443-c7efeb00-067d-11eb-8fe3-05343c927d6b.png)

#### But when I use the normal watch mode of nest this is the error:

![imagen](https://user-images.githubusercontent.com/50024128/95030465-ee158b00-067d-11eb-84f3-66f6592aa194.png)

#### This is the template:

![imagen](https://user-images.githubusercontent.com/50024128/95030513-54021280-067e-11eb-9f80-abc1b2a91a71.png)

**Comment by pmb0** [comment]
Hi @Dav3rs ! Got your project working with this change:

```diff
diff --git a/tsconfig.json b/tsconfig.json
index 63869eb..3e93b15 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -1,5 +1,6 @@
 {
   "compilerOptions": {
+    "esModuleInterop": true,
     "module": "commonjs",
     "declaration": true,
     "removeComments": true,
```

I will note the `esModuleInterop` setting in the README.
