### ISSUE TITLE
NestJS -Failed to lookup view in views directory

### ISSUE THREAD

**Issue by thachp** [pmb0/express-tsx-views#85]
I believe I made mistakes, please take a look at my PR for NestJS example. I'm getting _Failed to lookup view error_, even though the file Index.tsx is there.

![image](https://user-images.githubusercontent.com/1495371/101473405-a4a41f00-38fe-11eb-8b89-b50878393860.png)

PR: https://github.com/pmb0/express-tsx-views/pull/84
Repros: https://github.com/thachp/express-tsx-views

**Comment by pmb0** [comment]
Hi @thachp , you have to fix your `viewsDirectory` or to configure a `baseUrl` in your `tsconfig.json`.

```diff
- viewsDirectory: resolve(__dirname, '../src/views'),
+ viewsDirectory: resolve(__dirname, './views'),
```

Your TSX files will be transpiled by `nest start:dev` and stored in `dist`. In your current configuration `dist` is built in such a way that there is no `src` directory there. For this reason no view can be found.

**Comment by thachp** [comment]
@pmb0  Yep that does it for me, it was a path issue.   It will be helpful if you can include this piece of info in the ReadMe.

> Your TSX files will be transpiled by nest start and stored in dist. In your current configuration dist is built in such a way that there is no src directory there. For this reason no view can be found.
